version: "3"

services:

  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: numer
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:5050"

  server:
    build: ./NumerAPI .
    container_name: server
    image: numer_server_image
    ports:
      - 3000:3000
    environment:
      SERVER_PORT: 3000
      POSTGRES_URL: postgres://root:root@db:5432/numer

  client:
    build: ./numer-web .
    container_name: client
    image: numer_client_image
    ports:
      - 5173:5173
    depends_on:
      - server
