name: Deploy
on:
  push:
    braches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Client
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./numer-web
          file: ./numer-web/Dockerfile
          push: true
          tags: richstardocker/numerical:latest